### PR TITLE
Bump `bw2io` to `0.8.10`

### PR DESCRIPTION
**Pull request by michaelweinold**
...getting ready for a PyPI and conda-forge release. As requested by the Activity Browser MVP @marc-vdm.

### CODE REVIEW

**Comment by michaelweinold** [comment]
https://github.com/LCA-ActivityBrowser/activity-browser/pull/1041

**Comment by romainsacchi** [comment]
Awesome, thanks a bunch @cmutel  @michaelweinold .

**Comment by marc-vdm** [comment]
Sorry to keep bothering you all with this @michaelweinold @cmutel, but could you also start the release process on [conda forge](https://github.com/conda-forge/brightway2-feedstock)? I thought this was automagic, but apparently not.

**Comment by michaelweinold** [comment]
Sure, I've opened https://github.com/conda-forge/bw2io-feedstock/pull/11

**Pull request merged**
